controllers/TransportController.php
<?php

namespace app\controllers;

use app\models\ConvertFile;
use app\models\enums\OrderStatus;
use app\models\Orders;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;

class TransportController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'index'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()

    {
        $files = scandir('transport/out');
        $orders = Orders::find()->where(['status'=>OrderStatus::IN_WORK])->all();
        foreach ($orders as $order) {
            if (!in_array($order->xls3,$files)) {
               $order->status = OrderStatus::LOADED;
               $order->save();
            }
        }
        return $this->render('index');
    }

    public function actionIndex2()
    {
        return $this->render('index2');

    }


    public function actionProcessing($file)
    {
        $orderNum = mb_substr($file,5,mb_strlen($file)-12);
        ConvertFile::readGTIN('transport/in/' . $file,'upload/' . $orderNum . '/'.'заказ' .$orderNum.'-1.xlsx');
        rename('transport/in/' . $file,'upload/' . $orderNum . '/'.'заказ' .$orderNum.'-2.xlsx');
        $order = Orders::find()->where(['id'=>$orderNum])->one();
        $order->status = OrderStatus::COMPLETE;
        $order->save();
        return $this->redirect(['transport/index2']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/transport/index.php
<?php

/* @var $this yii\web\View
 * @var $model MainUploadForm
 * @var $dataProvider ActiveDataProvider
 * @var $searchModel OrdersSearch
 */

use app\models\MainUploadForm;
use app\models\search\OrdersSearch;
use johnitvn\ajaxcrud\CrudAsset;
use yii\bootstrap\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;

CrudAsset::register($this);
$showFileAccess = \app\models\Settings::getValueFromKey('user_output_file_access');
$importers = \app\models\Importers::getImportersList();
$this->title = 'Обмен файлами';
$files = [];
$dir = 'transport/out/';
if ($handle = opendir($dir)) {
    while (false !== ($file = readdir($handle))) {
        if ($file != "." && $file != "..") {
            $files[] = [
                'name' => $file,
                'date' => date("d F Y H:i:s", filectime($dir . $file)),
                'size' => filesize($dir . $file) . ' байт',
            ];
        }
    }
} else {
    echo 'Ошибка открытия директории';
}
?>

<div role="tabpanel">
    <br><br><br>
    <!-- Навігаційні елементи вкладок -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><?= Html::a('Отправленные', ["/transport/index"]) ?></li>
        <li role="presentation"><?= Html::a('Полученные', ["/transport/index2"]) ?></li>
    </ul>

    <!-- Вкладки панелі -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <div class="user-index">
                <div class="panel panel-primary">
                    <div class="panel panel-heading">
                        <div class="row">
                            <div class="col-xs-3">Название</div>
                            <div class="col-xs-2">Дата</div>
                            <div class="col-xs-1">Размер</div>
                        </div>
                    </div>
                    <div class="panel panel-body">
                        <?php foreach ($files as $file) : ?>
                            <div class="row">
                                <div class="col-xs-3"><?= $file['name'] ?></div>
                                <div class="col-xs-2"><?= $file['date'] ?></div>
                                <div class="col-xs-1"><?= $file['size'] ?></div>
                            </div>

                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
        </div>
    </div>
</div>


<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/transport/index2.php
<?php

/* @var $this yii\web\View
 * @var $model MainUploadForm
 * @var $dataProvider ActiveDataProvider
 * @var $searchModel OrdersSearch
 */

use app\models\MainUploadForm;
use app\models\search\OrdersSearch;
use johnitvn\ajaxcrud\CrudAsset;
use yii\bootstrap\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;

CrudAsset::register($this);
$showFileAccess = \app\models\Settings::getValueFromKey('user_output_file_access');
$importers = \app\models\Importers::getImportersList();
$this->title = 'Обмен файлами';
$files = [];
$dir = 'transport/in/';
if ($handle = opendir($dir)) {
    while (false !== ($file = readdir($handle))) {
        if ($file != "." && $file != "..") {
            $files[] = [
                'name' => $file,
                'date' => date("d F Y H:i:s", filectime($dir . $file)),
                'size' => filesize($dir . $file) . ' байт',
            ];
        }
    }
} else {
    echo 'Ошибка открытия директории';
}
?>

<div role="tabpanel">
    <br><br><br>
    <!-- Навігаційні елементи вкладок -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" ><?= Html::a('Отправленные', ["/transport/index"]) ?></li>
        <li role="presentation" class="active"><?= Html::a('Полученные', ["/transport/index2"]) ?></li>
    </ul>

    <!-- Вкладки панелі -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <div class="user-index">
                <div class="panel panel-primary">
                    <div class="panel panel-heading">
                        <div class="row">
                            <div class="col-xs-3">Название</div>
                            <div class="col-xs-2">Дата</div>
                            <div class="col-xs-1">Размер</div>
                        </div>
                    </div>
                    <div class="panel panel-body">
                        <?php foreach ($files as $file) : ?>
                            <div class="row">
                                <div class="col-xs-3"><?= $file['name'] ?></div>
                                <div class="col-xs-2"><?= $file['date'] ?></div>
                                <div class="col-xs-1"><?= $file['size'] ?></div>
                                <div class="col-xs-1"><?= Html::a('<i class="glyphicon glyphicon-qrcode"></i>',['transport/processing','file'=>$file['name']]) ?></div>
                            </div>

                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
        </div>
    </div>
</div>


<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>
<?php
$script = <<<JS
$(".convert-xls").click(function() {
    console.log('asdas');
    $('.loading').show();
 });
JS;
$this->registerJs($script);
?>