controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\MainUploadForm;
use app\models\search\OrdersSearch;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'index'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user = Yii::$app->user->identity;
        /* @var $user User */
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $user->id);
        $dir = '';
        $model = new MainUploadForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->importer_id = Yii::$app->request->get('id');
            $model->file = UploadedFile::getInstance($model, 'inxls' . $model->importer_id);
            if ($model->file) {
                $model->save($user->id);
            }

        }
        return $this->render('index', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'dir' => $dir
        ]);

    }

    public function actionIndex2()
    {
        $user = Yii::$app->user->identity;
        /* @var $user User */
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $user->id);
        return $this->render('index2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View
 * @var $model MainUploadForm
 * @var $dataProvider ActiveDataProvider
 * @var $searchModel OrdersSearch
 */

use app\models\MainUploadForm;
use app\models\search\OrdersSearch;
use johnitvn\ajaxcrud\CrudAsset;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;

CrudAsset::register($this);
$showFileAccess = \app\models\Settings::getValueFromKey('user_output_file_access');
$importers = \app\models\Importers::getImportersList();
$this->title = 'Конвертация';
?>

<div role="tabpanel">
    <br><br><br>
    <!-- Навігаційні елементи вкладок -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><?= Html::a('Загрузка', ["/site/index"]) ?></li>
        <li role="presentation"><?= Html::a('Заказы', ["/site/index2"]) ?></li>
    </ul>

    <!-- Вкладки панелі -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <div class="user-index">
                <div class="loading"
                     style="position: absolute; z-index:10000; top: 50%; left: 50%; transform: translate(-50%, -50%);display: none">
                    <?= Html::img('/css/loading.gif'); ?>
                </div>
                <?php $form = ActiveForm::begin() ?>
                <div class="row">

                    <div class="col-md-6"><h3 class="box-title">СКИФ</h3>

                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, 'inxls1')->fileInput() ?>
                            </div>
                            <div class="col-md-6" style="padding-top: 25px">
                                <?= Html::submitButton('Конвертировать',
                                    [
                                        'class' => 'btn btn-primary convert-xls',
                                        'formaction' => Url::to([
                                            'site/' . Yii::$app->controller->action->id,
                                            'id' => 1
                                        ])
                                    ]); ?>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3 class="box-title">АЛЬЯНС</h3>
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, 'inxls2')->fileInput() ?>
                            </div>
                            <div class="col-md-5" style="padding-top: 25px">
                                <?= Html::submitButton('Конвертировать',
                                    [
                                        'class' => 'btn btn-primary convert-xls',
                                        'formaction' => Url::to([
                                            'site/' . Yii::$app->controller->action->id,
                                            'id' => 2
                                        ])
                                    ]) ?>
                            </div>

                        </div>
                    </div>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
        </div>
    </div>

</div>


<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>
<?php
$script = <<<JS
$(".convert-xls").click(function() {
    console.log('asdas');
    $('.loading').show();
 });
JS;
$this->registerJs($script);
?>

views/site/index2.php
<?php

/* @var $this yii\web\View
 * @var $model MainUploadForm
 * @var $dataProvider ActiveDataProvider
 * @var $searchModel OrdersSearch
 */

use app\models\enums\OrderStatus;
use app\models\MainUploadForm;
use app\models\Orders;
use app\models\search\OrdersSearch;
use johnitvn\ajaxcrud\CrudAsset;
use kartik\grid\GridView;
use yii\bootstrap\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;

CrudAsset::register($this);
$showFileAccess = \app\models\Settings::getValueFromKey('user_output_file_access');
$importers = \app\models\Importers::getImportersList();
$this->title = 'Конвертация';
?>

<div role="tabpanel">
    <br><br><br>
    <!-- Навігаційні елементи вкладок -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" ><?=Html::a('Загрузка',["site/index"])?></li>
        <li role="presentation" class="active"><?=Html::a('Заказы',["site/index2"])?></li>
    </ul>

    <!-- Вкладки панелі -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane" id="home">
        </div>
        <div role="tabpanel" class="tab-pane active" id="profile">
            <div class="countries-index">
                <div id="ajaxCrudDatatable">
                    <?= GridView::widget([
                        'id' => 'crud-datatable',
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'rowOptions' => function ($data) {
                            /* @var $data Orders */
                            if ($data->status == OrderStatus::COMPLETE) {
                                return ['style' => 'background-color:#fffebb'];
                            } elseif ($data->status == OrderStatus::IN_WORK) {
                                return ['style' => 'background-color:#bae1ff'];
                            } else {
                                return ['style' => 'background-color:#baffc9'];
                            }
                        },
                        'columns' => [
                            'id',
                            [
                                'attribute' => 'importer_id',
                                'filter' => $importers,
                                'value' => function ($data) use ($importers) {
                                    /* @var $data Orders */
                                    return $importers[$data->importer_id] ?? 'не задан';
                                }
                            ],
                            [
                                'attribute' => 'load_date',
                                'format' => ['date', 'php:d.m.Y'],
                            ],
                            [
                                'attribute' => 'status',
                                'filter' => OrderStatus::listData(),
                                'value' => function ($data) {
                                    /* @var $data Orders */
                                    return OrderStatus::getLabel($data->status);

                                }
                            ],
                            'count_position',
                            [
                                'class' => 'kartik\grid\ActionColumn',
                                'visible' => $showFileAccess == 1,
                                'header' => '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspДействия&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp',
                                'dropdown' => false,
                                'vAlign' => 'middle',
                                'urlCreator' => function ($action, $model, $key, $index) {
                                    return Url::to([$action, 'id' => $key]);
                                },
                                'template' => '{view} &nbsp {upload-input} &nbsp {upload-output1} &nbsp {upload-output2}',
                                'buttons' => [
                                    'upload-input' => function ($url, $data, $key) {
                                        return Html::a('<i class="glyphicon glyphicon-floppy-save"></i>', '/upload/'.$key.'/' . $data->xls1);
                                    },
                                    'upload-output1' => function ($url, $data, $key) {
                                        return Html::a('<i class="glyphicon glyphicon-floppy-save"></i>', '/upload/'.$key.'/' . $data->xls2);
                                    },
                                    'upload-output2' => function ($url, $data, $key) {
                                        return Html::a('<i class="glyphicon glyphicon-floppy-save"></i>', '/upload/'.$key.'/' . $data->xls3);
                                    },
                                ],
                                'viewOptions' => ['role' => 'modal-remote', 'title' => 'View', 'data-toggle' => 'tooltip'],
                            ],
                        ],
                        'toolbar' => [
                            [
                                'content' =>

                                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                                        ['data-pjax' => 1, 'class' => 'btn btn-default', 'title' => 'Reset Grid']) .
                                    '{toggleData}' .
                                    '{export}'
                            ],
                        ],
                        'striped' => true,
                        'condensed' => true,
                        'responsive' => true,
                        'panel' => [
                            'type' => 'primary',
                            'heading' => '<i class="glyphicon glyphicon-list"></i> Заказы',
                            'before' => '',
                            'after' => false,
                        ]
                    ]) ?>
                </div>
            </div>
        </div>
    </div>

</div>



<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>
<?php
$script = <<<JS
$("#convert-xls").click(function() {
    console.log('asdas');
    $('.loading').show();
 });
JS;
$this->registerJs($script);
?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1><?= Html::encode($this->title) ?></h1>

            <p>Заполните поля для входа:</p>

            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'layout' => 'horizontal',
                'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-lg-4\">{input}</div>\n<div class=\"col-lg-7\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
            ]); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>

            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>


</div>